export const allBosses = [
    "Asylum Demon",
    "Taurus Demon",
    "Bell Gargoyle",
    "Moonlight Butterfly",
    "Capra Demon",
    "Gaping Dragon",
    "Chaos Witch Quelaag",
    "Iron Golem",
    "Dark Sun Gwyndolin",
    "Crossbreed Priscilla",
    "Ornstein and Smough",
    "Stray Demon",
    "Ceaseless Discharge",
    "Demon Firesage",
    "Centipede Demon",
    "The Bed of Chaos",
    "Pinwheel",
    "Nito",
    "Seath the Scaleless",
    "Great Grey Wolf Sif",
    "Four Kings",
    "Sanctuary Guardian",
    "Black Dragon Kalameet",
    "Artorias the Abysswalker",
    "Manus, Father of the Abyss",
    "Gwyn Lord of Cinder",
];
