export const allBosses = [
    "The Last Giant",
    "The Pursuer",
    "Dragonrider",
    "Old Dragonslayer",
    "Flexile Sentry",
    "Ruin Sentinel",
    "Belfry Gargoyles",
    "Lost Sinner",
    "The Skeleton Lords",
    "Executioner's Chariot",
    "Covetous Demon",
    "Mytha, the Baneful Queen",
    "Smelter Demon",
    "Old Iron King",
    "Royal Rat Vanguard",
    "The Rotten",
    "Scorpioness Najka",
    "Royal Rat Authority",
    "Prowling Magus and Congregation",
    "The Duke's Dear Freja",
    "Twin Dragonrider",
    "Looking Glass Knight",
    "Demon of Song",
    "Velstadt, the Royal Aegis",
    "Giant Lord",
    "Vendrick",
    "Guardian Dragon",
    "Ancient Dragon",
    "Darklurker",
    "Throne Watcher and Throne Defender",
    "Nashandra",
    "Aldia, Scholar of the First Sin",
    "Graverobber, Varg, and Cerah",
    "Elana, Squalid Queen",
    "Sinh, the Slumbering Dragon",
    "Blue Smelter Demon",
    "Fume Knight",
    "Sir Alonne",
    "Aava, the King's Pet",
    "Lud and Zallen, the King's Pets",
    "Burnt Ivory King"
];